export type AvatarCategory =
  | 'protagonist'
  | 'rival'
  | 'gym-leader'
  | 'elite'
  | 'villain'
  | 'professor'
  | 'frontier'
  | 'notable';

export interface AvatarCharacter {
  id: string;
  name: string;
  category: AvatarCategory;
}

export const AVATAR_CHARACTERS: AvatarCharacter[] = [
  // ── Protagonists ──────────────────────────────────────
  { id: 'red', name: 'Red', category: 'protagonist' },
  { id: 'leaf-gen3', name: 'Leaf', category: 'protagonist' },
  { id: 'ethan', name: 'Ethan', category: 'protagonist' },
  { id: 'kris', name: 'Kris', category: 'protagonist' },
  { id: 'lyra', name: 'Lyra', category: 'protagonist' },
  { id: 'brendan', name: 'Brendan', category: 'protagonist' },
  { id: 'may', name: 'May', category: 'protagonist' },
  { id: 'lucas', name: 'Lucas', category: 'protagonist' },
  { id: 'dawn', name: 'Dawn', category: 'protagonist' },
  { id: 'hilbert', name: 'Hilbert', category: 'protagonist' },
  { id: 'hilda', name: 'Hilda', category: 'protagonist' },
  { id: 'nate', name: 'Nate', category: 'protagonist' },
  { id: 'calem', name: 'Calem', category: 'protagonist' },
  { id: 'elio', name: 'Elio', category: 'protagonist' },
  { id: 'elaine', name: 'Elaine', category: 'protagonist' },
  { id: 'chase', name: 'Chase', category: 'protagonist' },
  { id: 'gloria', name: 'Gloria', category: 'protagonist' },
  { id: 'florian-s', name: 'Florian', category: 'protagonist' },
  { id: 'juliana-s', name: 'Juliana', category: 'protagonist' },
  { id: 'akari', name: 'Akari', category: 'protagonist' },
  { id: 'ash', name: 'Ash', category: 'protagonist' },
  { id: 'liko', name: 'Liko', category: 'protagonist' },

  // ── Rivals ────────────────────────────────────────────
  { id: 'blue', name: 'Blue', category: 'rival' },
  { id: 'green', name: 'Green', category: 'rival' },
  { id: 'barry', name: 'Barry', category: 'rival' },
  { id: 'bianca', name: 'Bianca', category: 'rival' },
  { id: 'cheren', name: 'Cheren', category: 'rival' },
  { id: 'hugh', name: 'Hugh', category: 'rival' },
  { id: 'n', name: 'N', category: 'rival' },
  { id: 'gladion', name: 'Gladion', category: 'rival' },
  { id: 'hau', name: 'Hau', category: 'rival' },
  { id: 'hop', name: 'Hop', category: 'rival' },
  { id: 'bede', name: 'Bede', category: 'rival' },
  { id: 'marnie', name: 'Marnie', category: 'rival' },
  { id: 'avery', name: 'Avery', category: 'rival' },
  { id: 'klara', name: 'Klara', category: 'rival' },
  { id: 'nemona-s', name: 'Nemona', category: 'rival' },
  { id: 'penny', name: 'Penny', category: 'rival' },
  { id: 'arven-s', name: 'Arven', category: 'rival' },
  { id: 'kieran', name: 'Kieran', category: 'rival' },
  { id: 'carmine', name: 'Carmine', category: 'rival' },

  // ── Gym Leaders ───────────────────────────────────────
  // Kanto
  { id: 'brock', name: 'Brock', category: 'gym-leader' },
  { id: 'misty', name: 'Misty', category: 'gym-leader' },
  { id: 'ltsurge', name: 'Lt. Surge', category: 'gym-leader' },
  { id: 'erika', name: 'Erika', category: 'gym-leader' },
  { id: 'koga', name: 'Koga', category: 'gym-leader' },
  { id: 'janine', name: 'Janine', category: 'gym-leader' },
  { id: 'blaine', name: 'Blaine', category: 'gym-leader' },
  // Johto
  { id: 'falkner', name: 'Falkner', category: 'gym-leader' },
  { id: 'bugsy', name: 'Bugsy', category: 'gym-leader' },
  { id: 'morty', name: 'Morty', category: 'gym-leader' },
  { id: 'chuck', name: 'Chuck', category: 'gym-leader' },
  { id: 'jasmine', name: 'Jasmine', category: 'gym-leader' },
  { id: 'clair', name: 'Clair', category: 'gym-leader' },
  // Hoenn
  { id: 'brawly', name: 'Brawly', category: 'gym-leader' },
  { id: 'flannery', name: 'Flannery', category: 'gym-leader' },
  { id: 'norman', name: 'Norman', category: 'gym-leader' },
  { id: 'liza', name: 'Liza', category: 'gym-leader' },
  { id: 'juan', name: 'Juan', category: 'gym-leader' },
  // Sinnoh
  { id: 'gardenia', name: 'Gardenia', category: 'gym-leader' },
  { id: 'maylene', name: 'Maylene', category: 'gym-leader' },
  { id: 'crasherwake', name: 'Crasher Wake', category: 'gym-leader' },
  { id: 'fantina', name: 'Fantina', category: 'gym-leader' },
  { id: 'byron', name: 'Byron', category: 'gym-leader' },
  { id: 'candice', name: 'Candice', category: 'gym-leader' },
  // Unova
  { id: 'cilan', name: 'Cilan', category: 'gym-leader' },
  { id: 'chili', name: 'Chili', category: 'gym-leader' },
  { id: 'cress', name: 'Cress', category: 'gym-leader' },
  { id: 'lenora', name: 'Lenora', category: 'gym-leader' },
  { id: 'burgh', name: 'Burgh', category: 'gym-leader' },
  { id: 'elesa', name: 'Elesa', category: 'gym-leader' },
  { id: 'clay', name: 'Clay', category: 'gym-leader' },
  { id: 'brycen', name: 'Brycen', category: 'gym-leader' },
  { id: 'drayden', name: 'Drayden', category: 'gym-leader' },
  { id: 'marlon', name: 'Marlon', category: 'gym-leader' },
  // Kalos
  { id: 'grant', name: 'Grant', category: 'gym-leader' },
  { id: 'korrina', name: 'Korrina', category: 'gym-leader' },
  { id: 'clemont', name: 'Clemont', category: 'gym-leader' },
  { id: 'olympia', name: 'Olympia', category: 'gym-leader' },
  // Alola
  { id: 'ilima', name: 'Ilima', category: 'gym-leader' },
  { id: 'lana', name: 'Lana', category: 'gym-leader' },
  { id: 'mallow', name: 'Mallow', category: 'gym-leader' },
  { id: 'nanu', name: 'Nanu', category: 'gym-leader' },
  { id: 'mina', name: 'Mina', category: 'gym-leader' },
  // Galar
  { id: 'milo', name: 'Milo', category: 'gym-leader' },
  { id: 'nessa', name: 'Nessa', category: 'gym-leader' },
  { id: 'kabu', name: 'Kabu', category: 'gym-leader' },
  { id: 'bea', name: 'Bea', category: 'gym-leader' },
  { id: 'allister', name: 'Allister', category: 'gym-leader' },
  { id: 'gordie', name: 'Gordie', category: 'gym-leader' },
  { id: 'melony', name: 'Melony', category: 'gym-leader' },
  { id: 'piers', name: 'Piers', category: 'gym-leader' },
  // Paldea
  { id: 'katy', name: 'Katy', category: 'gym-leader' },
  { id: 'brassius', name: 'Brassius', category: 'gym-leader' },
  { id: 'iono', name: 'Iono', category: 'gym-leader' },
  { id: 'kofu', name: 'Kofu', category: 'gym-leader' },
  { id: 'larry', name: 'Larry', category: 'gym-leader' },
  { id: 'grusha', name: 'Grusha', category: 'gym-leader' },
  { id: 'hassel', name: 'Hassel', category: 'gym-leader' },

  // ── Elite Four & Champions ────────────────────────────
  { id: 'lorelei-gen3', name: 'Lorelei', category: 'elite' },
  { id: 'bruno', name: 'Bruno', category: 'elite' },
  { id: 'agatha-gen3', name: 'Agatha', category: 'elite' },
  { id: 'lance', name: 'Lance', category: 'elite' },
  { id: 'karen', name: 'Karen', category: 'elite' },
  { id: 'glacia', name: 'Glacia', category: 'elite' },
  { id: 'drake-gen3', name: 'Drake', category: 'elite' },
  { id: 'phoebe-gen3', name: 'Phoebe', category: 'elite' },
  { id: 'aaron', name: 'Aaron', category: 'elite' },
  { id: 'bertha', name: 'Bertha', category: 'elite' },
  { id: 'flint', name: 'Flint', category: 'elite' },
  { id: 'lucian', name: 'Lucian', category: 'elite' },
  { id: 'cynthia', name: 'Cynthia', category: 'elite' },
  { id: 'marshal', name: 'Marshal', category: 'elite' },
  { id: 'grimsley', name: 'Grimsley', category: 'elite' },
  { id: 'caitlin', name: 'Caitlin', category: 'elite' },
  { id: 'alder', name: 'Alder', category: 'elite' },
  { id: 'iris', name: 'Iris', category: 'elite' },
  { id: 'malva', name: 'Malva', category: 'elite' },
  { id: 'drasna', name: 'Drasna', category: 'elite' },
  { id: 'diantha', name: 'Diantha', category: 'elite' },
  { id: 'hala', name: 'Hala', category: 'elite' },
  { id: 'olivia', name: 'Olivia', category: 'elite' },
  { id: 'acerola', name: 'Acerola', category: 'elite' },
  { id: 'kahili', name: 'Kahili', category: 'elite' },
  { id: 'molayne', name: 'Molayne', category: 'elite' },
  { id: 'leon', name: 'Leon', category: 'elite' },
  { id: 'mustard', name: 'Mustard', category: 'elite' },
  { id: 'peony', name: 'Peony', category: 'elite' },
  { id: 'geeta', name: 'Geeta', category: 'elite' },
  { id: 'crispin', name: 'Crispin', category: 'elite' },
  { id: 'lacey', name: 'Lacey', category: 'elite' },
  { id: 'drayton', name: 'Drayton', category: 'elite' },
  { id: 'amarys', name: 'Amarys', category: 'elite' },

  // ── Villains & Evil Teams ─────────────────────────────
  { id: 'giovanni', name: 'Giovanni', category: 'villain' },
  { id: 'archer', name: 'Archer', category: 'villain' },
  { id: 'ariana', name: 'Ariana', category: 'villain' },
  { id: 'petrel', name: 'Petrel', category: 'villain' },
  { id: 'jessiejames-gen1', name: 'Jessie & James', category: 'villain' },
  { id: 'archie-gen6', name: 'Archie', category: 'villain' },
  { id: 'matt', name: 'Matt', category: 'villain' },
  { id: 'maxie-gen6', name: 'Maxie', category: 'villain' },
  { id: 'courtney', name: 'Courtney', category: 'villain' },
  { id: 'cyrus', name: 'Cyrus', category: 'villain' },
  { id: 'mars', name: 'Mars', category: 'villain' },
  { id: 'jupiter', name: 'Jupiter', category: 'villain' },
  { id: 'charon', name: 'Charon', category: 'villain' },
  { id: 'ghetsis', name: 'Ghetsis', category: 'villain' },
  { id: 'colress', name: 'Colress', category: 'villain' },
  { id: 'lysandre', name: 'Lysandre', category: 'villain' },
  { id: 'bryony', name: 'Bryony', category: 'villain' },
  { id: 'mable', name: 'Mable', category: 'villain' },
  { id: 'plumeria', name: 'Plumeria', category: 'villain' },
  { id: 'guzma', name: 'Guzma', category: 'villain' },
  { id: 'lusamine', name: 'Lusamine', category: 'villain' },
  { id: 'faba', name: 'Faba', category: 'villain' },
  { id: 'oleana', name: 'Oleana', category: 'villain' },
  { id: 'mela', name: 'Mela', category: 'villain' },
  { id: 'giacomo', name: 'Giacomo', category: 'villain' },
  { id: 'atticus', name: 'Atticus', category: 'villain' },
  { id: 'ortega', name: 'Ortega', category: 'villain' },
  { id: 'eri', name: 'Eri', category: 'villain' },
  { id: 'arlo', name: 'Arlo', category: 'villain' },
  { id: 'cliff', name: 'Cliff', category: 'villain' },

  // ── Professors ────────────────────────────────────────
  { id: 'oak', name: 'Prof. Oak', category: 'professor' },
  { id: 'elm', name: 'Prof. Elm', category: 'professor' },
  { id: 'birch', name: 'Prof. Birch', category: 'professor' },
  { id: 'juniper', name: 'Prof. Juniper', category: 'professor' },
  { id: 'kukui', name: 'Prof. Kukui', category: 'professor' },
  { id: 'magnolia', name: 'Prof. Magnolia', category: 'professor' },
  { id: 'laventon', name: 'Prof. Laventon', category: 'professor' },
  { id: 'jacq', name: 'Jacq', category: 'professor' },
  { id: 'burnet', name: 'Prof. Burnet', category: 'professor' },

  // ── Battle Frontier ───────────────────────────────────
  { id: 'palmer', name: 'Palmer', category: 'frontier' },
  { id: 'dahlia', name: 'Dahlia', category: 'frontier' },
  { id: 'darach', name: 'Darach', category: 'frontier' },
  { id: 'argenta', name: 'Argenta', category: 'frontier' },
  { id: 'noland', name: 'Noland', category: 'frontier' },
  { id: 'brandon', name: 'Brandon', category: 'frontier' },
  { id: 'lucy', name: 'Lucy', category: 'frontier' },
  { id: 'greta', name: 'Greta', category: 'frontier' },
  { id: 'anabel', name: 'Anabel', category: 'frontier' },
  { id: 'emmet', name: 'Emmet', category: 'frontier' },
  { id: 'ingo', name: 'Ingo', category: 'frontier' },
  { id: 'evelyn', name: 'Evelyn', category: 'frontier' },

  // ── Notable Characters ────────────────────────────────
  { id: 'lillie', name: 'Lillie', category: 'notable' },
  { id: 'lisia', name: 'Lisia', category: 'notable' },
  { id: 'cheryl', name: 'Cheryl', category: 'notable' },
  { id: 'marley', name: 'Marley', category: 'notable' },
  { id: 'mira', name: 'Mira', category: 'notable' },
  { id: 'buck', name: 'Buck', category: 'notable' },
  { id: 'fennel', name: 'Fennel', category: 'notable' },
  { id: 'bill', name: 'Bill', category: 'notable' },
  { id: 'kurt', name: 'Kurt', category: 'notable' },
  { id: 'eusine', name: 'Eusine', category: 'notable' },
  { id: 'johanna', name: 'Johanna', category: 'notable' },
  { id: 'cogita', name: 'Cogita', category: 'notable' },
  { id: 'irida', name: 'Irida', category: 'notable' },
  { id: 'adaman', name: 'Adaman', category: 'notable' },
  { id: 'kamado', name: 'Kamado', category: 'notable' },
  { id: 'mai', name: 'Mai', category: 'notable' },
  { id: 'arezu', name: 'Arezu', category: 'notable' },
  { id: 'iscan', name: 'Iscan', category: 'notable' },
  { id: 'lian', name: 'Lian', category: 'notable' },
  { id: 'gaeric', name: 'Gaeric', category: 'notable' },
  { id: 'melli', name: 'Melli', category: 'notable' },
  { id: 'hapu', name: 'Hapu', category: 'notable' },
  { id: 'alain', name: 'Alain', category: 'notable' },
  { id: 'gurkinn', name: 'Gurkinn', category: 'notable' },
  { id: 'az', name: 'AZ', category: 'notable' },
  { id: 'grace', name: 'Grace', category: 'notable' },
  { id: 'dexio', name: 'Dexio', category: 'notable' },
  { id: 'emma', name: 'Emma', category: 'notable' },
  { id: 'benga', name: 'Benga', category: 'notable' },
  { id: 'concordia', name: 'Concordia', category: 'notable' },
  { id: 'anthea', name: 'Anthea', category: 'notable' },
  { id: 'clavell-s', name: 'Clavell', category: 'notable' },
  { id: 'briar', name: 'Briar', category: 'notable' },
  { id: 'perrin', name: 'Perrin', category: 'notable' },
  { id: 'blanche', name: 'Blanche', category: 'notable' },
  { id: 'candela', name: 'Candela', category: 'notable' },
  { id: 'mohn', name: 'Mohn', category: 'notable' },
  { id: 'palina', name: 'Palina', category: 'notable' },
  { id: 'peonia', name: 'Peonia', category: 'notable' },
];

export const AVATAR_CATEGORIES = [
  'protagonist',
  'rival',
  'gym-leader',
  'elite',
  'villain',
  'professor',
  'frontier',
  'notable',
] as const;

const AVATAR_BASE_URL = 'https://play.pokemonshowdown.com/sprites/trainers';

export function getAvatarUrl(id: string): string {
  return `${AVATAR_BASE_URL}/${id}.png`;
}
